# This is a basic workflow to help you get started with Actions

name: 'CI-build'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - 'main'
      - 'master'
      - 'v-*'
      - 'release/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-22.04
    #    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      #        with:
      #          submodules: recursive
      #          token: ${{ secrets.PAT_TOKEN }}

      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .gradle
            .kotlin
          key: ${{ runner.os }}-primes

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle from Properties File
        uses: gradle/actions/setup-gradle@v5

#      # https://github.com/actions/runner-images/issues/675
#      - name: Hack sources.list
#        run: sudo sed -i 's|http://azure.archive.ubuntu.com/ubuntu/|http://mirror.arizona.edu/ubuntu/|g' /etc/apt/sources.list
#
#      - name: Install curl-dev
#        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libpq-dev libpq5

      - name: Build Infrastructure
        run: gradle buildInfra --info --build-cache
#        - name: Build App Images
#          run gradle buildImages --info --build-cache
      - name: Run E2E Tests
        run: gradle e2eTests --info --build-cache
